version: "3.9"

services:
  api:
    container_name: docapi
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "50123:8435"
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8435/docs >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
